name: CI/CD Django on Redis database
on:
  push:
    branches:
      - main

jobs:
  app_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip

      - name: Install pylint
        run: |
          pip install pylint

      - name: Analysing the code with pylint
        run: |
          pylint --disable=C0411 --disable=C0114 --disable=C0116 --disable=E0401  djangoapp/myapp/views.py

  app_push:
    needs: app_build
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker image
        run: |
          docker build -t mariusares/cct-django -f djangoapp/Dockerfile djangoapp

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag Docker image for Docker Hub
        run: |
          docker tag mariusares/cct-django:latest ${{ secrets.DOCKER_USERNAME }}/cct-django:latest

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/cct-django:latest

  app_deploy:
    needs: app_push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Docker container
        run: |
          docker run -d -p 8000:8000 ${{ secrets.DOCKER_USERNAME }}/cct-django:latest
